application: cttestblog
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: images

- url: /(.*\.(html|ico|png|jpg|gif))
  static_files: static/\1
  upload: static/(.*\.(html|ico|png|jpg|gif))

- url: /tasks/cleanup
  script: cleanup.py

- url: /.*
  script: blog.py

skip_files:
  ^cmd\/.*
  ^\.hg*
  ^\/raw.*
