application: guest-kks
version: 4
runtime: python
api_version: 1

handlers:
- url: /favicon\.ico
  static_files: images/favicon.ico

- url: /images
  static_dir: images

- url: /images/(.*)
  static_files: images/\1
  upload: images/(.*)

- url: /.*
  script: guestbook.py

